"""
ReportLab document generation service for OrganicLink.
Generates:
1. Quality Inspection Certificates (PDF)
2. Order Invoices with embedded quality summary and variance breakdown (PDF)
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

UPLOADS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "uploads")
PDF_DIR = os.path.join(UPLOADS_DIR, "pdf")
os.makedirs(PDF_DIR, exist_ok=True)


def generate_quality_certificate_pdf(inspection_data: dict, farm_name: str, product_name: str) -> str:
    """
    Generates a formal PDF Quality Inspection Certificate.
    Returns relative filepath for serving.
    """
    filename = f"cert_{inspection_data['id'][:8]}.pdf"
    filepath = os.path.join(PDF_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CertTitle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=colors.HexColor('#1b4332'),
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        'CertSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#2d6a4f'),
        spaceAfter=20
    )

    story = []
    story.append(Paragraph("ORGANICLINK QUALITY CERTIFICATE", title_style))
    story.append(Paragraph(f"Official Organic Inspection Certificate | Issued by AI Quality Grading Engine", subtitle_style))
    story.append(Spacer(1, 10))

    # Certificate Details Table
    table_data = [
        ["Inspection ID:", inspection_data.get("id", "N/A"), "Inspection Level:", inspection_data.get("inspection_level", "farm").upper()],
        ["Farm Name:", farm_name, "Product Type:", product_name],
        ["Quality Score:", f"{inspection_data.get('quality_score', 0):.1f} / 100", "Quality Grade:", f"GRADE {inspection_data.get('quality_grade', 'N/A')}"],
        ["Model Version:", inspection_data.get("model_version", "effnetb0-v1"), "Confidence:", f"{inspection_data.get('model_confidence', 0):.1f}%"],
        ["Date & Time:", str(inspection_data.get("created_at", datetime.utcnow().strftime("%Y-%m-%d %H:%M"))), "Defects Detected:", ", ".join(inspection_data.get("defects_detected", [])) or "None"]
    ]

    t = Table(table_data, colWidths=[120, 150, 120, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f7fee7')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#14532d')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#86efac')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))

    # Sub-metrics Breakdown
    cv_res = inspection_data.get("cv_results", {})
    if cv_res:
        story.append(Paragraph("<b>Computer Vision Visual Analysis Breakdown:</b>", styles['Heading2']))
        metrics_data = [
            ["Metric", "Value", "Benchmark"],
            ["Colour Vibrancy (HSV Saturation)", f"{cv_res.get('colour_vibrancy', 0):.1f} / 100", ">= 60.0"],
            ["Colour Uniformity (Hue Consistency)", f"{cv_res.get('colour_uniformity', 0):.1f} / 100", ">= 70.0"],
            ["Brightness Index", f"{cv_res.get('brightness', 0):.1f} / 100", ">= 50.0"],
            ["Defect Coverage Proxy", f"{cv_res.get('defect_coverage_percent', 0):.2f}%", "<= 5.0%"]
        ]
        mt = Table(metrics_data, colWidths=[200, 150, 150])
        mt.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2d6a4f')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#dcfce7')),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(mt)

    # Footer note
    story.append(Spacer(1, 30))
    story.append(Paragraph("<font size=9 color='#666666'>This digital certificate is generated by OrganicLink Ireland's AI Inspection Engine. Certified 100% Organic Origin.</font>", styles['Normal']))

    doc.build(story)
    return f"/static/pdf/{filename}"


def generate_invoice_pdf(order_data: dict, farmer_data: dict, buyer_data: dict) -> str:
    """
    Generates a formal PDF Invoice embedding order pricing and the quality variance breakdown.
    """
    filename = f"invoice_{order_data['id'][:8]}.pdf"
    filepath = os.path.join(PDF_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'InvoiceTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#15803d'),
        spaceAfter=6
    )

    story = []
    story.append(Paragraph("ORGANICLINK OFFICIAL INVOICE", title_style))
    story.append(Paragraph(f"Invoice Reference: INV-{order_data['id'][:8].upper()} | Status: {order_data.get('status', 'pending').upper()}", styles['Normal']))
    story.append(Spacer(1, 15))

    # Seller & Buyer info table
    party_data = [
        ["SELLER (FARMER):", "BUYER:"],
        [f"{farmer_data.get('farm_name', 'Organic Farm')}\n{farmer_data.get('town')}, Co. {farmer_data.get('county')}\nOrganic Cert #: {farmer_data.get('organic_cert_number', 'IOA-10294')}",
         f"{buyer_data.get('name', 'Buyer')}\n{order_data.get('delivery_address', 'Ireland')}\nRole: {buyer_data.get('role', 'buyer').title()}"]
    ]
    pt = Table(party_data, colWidths=[270, 270])
    pt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0fdf4')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#166534')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#bbf7d0')),
    ]))
    story.append(pt)
    story.append(Spacer(1, 15))

    # Order Line Items
    items_data = [
        ["Product", "Quantity", "Price / Unit", "Total Price (€)"],
        [
            f"Organic {order_data.get('product_type', 'Produce').title()}",
            f"{order_data.get('quantity', 0)} {order_data.get('quantity_unit', 'kg')}",
            f"€{order_data.get('price_per_unit', 0):.2f}",
            f"€{order_data.get('total_price', 0):.2f}"
        ]
    ]
    it = Table(items_data, colWidths=[200, 100, 120, 120])
    it.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#166534')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#dcfce7')),
    ]))
    story.append(it)
    story.append(Spacer(1, 15))

    # Embedded Quality Summary & Variance Breakdown
    story.append(Paragraph("<b>Quality Assurance & Variance Audit:</b>", styles['Heading3']))
    variance_pct = order_data.get("quality_variance_percent")
    var_str = f"{variance_pct:+.2f}%" if variance_pct is not None else "N/A"
    pass_flag = "PASS (Within +-10% Tolerance)" if order_data.get("variance_acceptable") else "DISPUTED / UNDER REVIEW"

    quality_data = [
        ["Farm Inspection Grade:", order_data.get("farm_grade", "A"), "Delivery Inspection Grade:", order_data.get("delivery_grade", "A")],
        ["Quality Variance:", var_str, "Quality Tolerance Status:", pass_flag]
    ]
    qt = Table(quality_data, colWidths=[140, 130, 140, 130])
    qt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fefce8')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#854d0e')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#fef08a')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(qt)

    story.append(Spacer(1, 25))
    story.append(Paragraph("Payment Terms: SEPA Direct Bank Transfer / Platform Escrow Settlement.", styles['Normal']))

    doc.build(story)
    return f"/static/pdf/{filename}"
